#!/bin/bash

set -o errexit # if any command fails any reason, script fails
set -o pipefail # if none of of you pipecommand fails, exit fails
set -o nounset # if none of variables set, exit

export DATABASE_URL="${DB_SCHEME}://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"

postgres_ready() {
python << END
import sys
import psycopg2
try:
    psycopg2.connect(
        user="${POSTGRES_USER}",
        password="${POSTGRES_PASSWORD}",
        host="${POSTGRES_HOST}",
        port="${POSTGRES_PORT}",
        dbname="${POSTGRES_DB}",
    )
except psycopg2.OperationalError:
    sys.exit(-1)
sys.exit(0)
END
}

until postgres_ready; do
>&2 echo "Waiting for PostgreSQL to become available... 8-(("
sleep 1
done
>&2 echo "PostgreSQL is ready!!! 8-))"

exec "$@"
